Add Windows support when processing paths
udayvir-singh/tangerine.nvim pull request #29
Opened 2023-08-23 14:57 UTC by Sharparam

Fixes #25

Finally got around to preparing this properly, apologies for the delay!

I've done some basic testing and it seems to work fine, but I'm marking this as a draft for now to test it a bit more first.

Feel free to check through the code though to see if it looks good!

2023-08-23 18:14 UTC, Sharparam commented
Ok there we go, fixed it up. Should look much better now!

Still need to do a bit more proper test in the Windows environment at work, so I'll leave it as a draft still.

2023-08-24 09:37 UTC, udayvir-singh commented
@Sharparam Just reviewed your code, there is too much duplication going on, with the only difference being a `/` and `[\\/]` in regex, so you can just define the following functions and remove duplicating so much code:

```fennel
;; extract windows? as a module level variable because it makes the code easy to test
(local windows? (= _G.jit.os "Windows"))

;; export functions so that other modules can use them in case they need it in future
(lambda p.match [path pattern]
  "matches 'path' against 'pattern' with support for windows."
  (if windows?
    (path:match (pattern:gsub "/" "[\\/]"))
    (path:match pattern)))

(lambda p.gsub [path pattern repl]
  "substitutes 'pattern' in 'path' for 'repl' with support for windows."
  (if windows?
    (path:gsub (pattern:gsub "/" "[\\/]") repl)
    (path:gsub pattern repl)))
```

Then you can just use these functions, like this:
```fennel
(lambda p.shortname [path]
  "shortens absolute 'path' for better readability."
  (or (p.match path ".+/fnl/(.+)")
      (p.match path ".+/lua/(.+)")
      (p.match path ".+/(.+/.+)")))
```

2023-08-24 09:42 UTC, udayvir-singh commented
This is fine:
```diff
 (lambda fs.write [path content]
   "writes string of 'content' to 'path'."
-  (local dir (path:match "(.*/)"))
+  (local dir (if (= _G.jit.os "Windows")
+                 (path:match "(.*[/\\])")
+                 (path:match "(.*/)")))
```
No need to add a abstraction here. Only change the code in `path` module.

2023-08-24 22:24 UTC, Sharparam commented
Thanks, that does look much better. I've applied the suggestions and just need to verify it all loads properly in my Windows environment again.

2023-08-25 08:36 UTC, udayvir-singh commented on fnl/tangerine/utils/path.fnl
>             (path:gsub from to)
I think there could be a bug in line 50 and 51, you should use `p.match` instead of `path:find` and `p.gsub` instead of `path:gsub` just to be sure.

2023-08-25 08:37 UTC, udayvir-singh commented on fnl/tangerine/utils/path.fnl
> +    (path:gsub pattern repl)))
put this entire block of code under `Utils` header and not on the top level, top level is reserved for imports and module definition only.

2023-08-25 08:44 UTC, udayvir-singh requested changes
The code seems good to be merged other the placement of utils in `path` module, I will merge the PR after it is place correctly under `Utils`.

2023-08-25 13:33 UTC, Sharparam commented
I've moved the code to the proper place now and tested that it works in my Windows environment, although I won't be able to run the Makefile proper until I'm back at home.

2023-08-25 14:35 UTC, udayvir-singh approved these changes

2023-08-26 13:54 UTC, Sharparam commented
And there we go, all ready to go :)

2023-08-27 10:23 UTC, merged